version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  api-gateway:
    build: ./api-gateway
    image: le098/socialmediaapp-api-gateway:latest
    ports:
      - "5000:5000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_URL: "redis://redis:6379"
      RABBITMQ_URL: "amqp://rabbitmq:5672"

  user-service:
    build: ./user-service
    image: le098/socialmediaapp-user-service:latest
    ports:
      - "5001:5001"
    env_file:
      - ./user-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_URL: "redis://redis:6379"
      RABBITMQ_URL: "amqp://rabbitmq:5672"

  post-service:
    build: ./post-service
    image: le098/socialmediaapp-post-service:latest
    ports:
      - "5002:5002"
    env_file:
      - ./post-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_URL: "redis://redis:6379"
      RABBITMQ_URL: "amqp://rabbitmq:5672"

  media-service:
    build: ./media-service
    image: le098/socialmediaapp-media-service:latest
    ports:
      - "5003:5003"
    env_file:
      - ./media-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_URL: "redis://redis:6379"
      RABBITMQ_URL: "amqp://rabbitmq:5672"

  search-service:
    build: ./search-service
    image: le098/socialmediaapp-search-service:latest
    ports:
      - "5004:5004"
    env_file:
      - ./search-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_URL: "redis://redis:6379"
      RABBITMQ_URL: "amqp://rabbitmq:5672"
